import react from "react";
import { StyledAbout } from "../styles/about.styles";
import Head from "next/head";

const about = () => {
  return (
    <>
      <Head>
        <title>The Arabian</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      </Head>
      <StyledAbout>
        <img id="AboutImage" src="/englishHeader.svg" alt="Site Header" />
        <p id="AboutDesc">
          The Arabian is a website dedicated for spreading the Arabic and
          Islamic culture{" "}
        </p>
        <p id="AboutCreator">Created by Ahmed Tarek Moftah</p>
      </StyledAbout>
    </>
  );
};
export default about;
