import Head from "next/head";
import Image from "next/image";
import WelcomeCard from "../components/WelcomeCard";
import styles from "../styles/Home.module.css";
import PlacesCards from "../components/PlacesCards";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>The Arabian</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      </Head>

      <main className={styles.main}>
        <WelcomeCard character={true} largeImg={false} />
        <PlacesCards />
      </main>
    </div>
  );
}
